= Curriculum Vitae - Michaël Bitard
Michaël Bitard <bitard.michael@gmail.com>
v1, 2019-03-13
:toc2:
:toclevels: 2
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:experimental:
:source-language: asciidoc
:includedir: _includes
// Refs
:link-31: https://goo.gl/maps/FhBLqfgD3DR2
:link-easymile: http://www.easymile.com/
:link-oauth2_proxy: https://github.com/bitly/oauth2_proxy
:link-viveris: https://www.viveris.fr/
:link-openbach: http://www.openbach.org
:link-marlink: https://marlink.com/
:link-living-objects: https://livingobjects.com/
:link-open-source-docker-images: https://github.com/agileek/docker
:link-open-source-agileek: https://github.com/agileek
:link-blog: https://agileek.github.io/



:link-elastic: https://www.elastic.co/
:link-exo: http://www.exoplatform.com/
:link-sre: http://www.pensions.bercy.gouv.fr/
:link-ausy: http://www.ausy.com/language/en
:link-sii: http://www.sii.fr/en
:link-bodet: http://www.bodet-software.com/en/time-attendance/time-and-attendance.html
:link-cogitec1: http://cogitec.fr
:link-cogitec2: http://cogitec.fr/Cogitec/realisation.cogitec
:link-blog: http://mgreau.com/blog.html
:link-adeditor-code: https://github.com/mgreau/when-websocket-met-asciidoctor
:link-resume-pdf: http://mgreau.com/resume/mgreau-resume.pdf
:link-podcast-asciidoctor: https://lescastcodeurs.com/2016/04/05/lcc-144-interview-asciidoctor-avec-maxime-greau-et-guillaume-scheibel/
:link-cast-codeurs: https://lescastcodeurs.com/
:link-adoc-editor-organization: https://github.com/adoc-editor


== Informations personnelles

[horizontal]
Nom:: Michaël Bitard
Social::
* http://michael.bitard.fr/[michael.bitard.fr, role="external", window="_blank"]
* `@BitardMichael` icon:twitter[link=https://twitter.com/BitardMichael, role="external", window="_blank", alt="@BitardMichael"] icon:github[link=https://github.com/MichaelBitard, role="external", window="_blank"] icon:linkedin[1x,link=https://www.linkedin.com/in/michaelbitard/, role="external", window="_blank"]
Adresse:: {link-31}["Toulouse, 31, FRANCE", role="external", window="_blank"]

== Expériences professionnelles

=== EasyMile

icon:calendar[title="Period"] `May 2017 -> Mars 2019` +
icon:group[title="Freelance"] {link-easymile}[EasyMile, role="external", window="_blank"] - Toulouse +
__EasyMile is one of the leading companies that specialises in autonomous vehicle technology.__

--
[horizontal]
Position:: *Devops & Backend & Frontend developer* +
Développeur sénior, R&D supervision de flottes de véhicules autonomes
--

* Release
** Improve production stack
** Cleanup the CI Workflow
** Integrate auth0 to {link-oauth2_proxy}["oauth2_proxy", role="external", window="_blank"]
* Mob programming
* Pair programming
* Frontend
** Migrate to styled-components
** Migrate to create-react-app
* Backend
** Ride sharing
** APis
* CI
** Jenkins nodes physically rebuilt from scratch using pxe
** Jenkins Read-only with job dsl and Jenkinsfiles

Technologies utilisées::

Docker, React, Elixir, Git, Jenkins, Kubernetes, Ansible, Go, Linux


=== Viveris

icon:calendar[title="Period"] `May 2016 -> Avril 2017` +
icon:group[title="Freelance"] {link-viveris}[Viveris, role="external", window="_blank"] - Toulouse +
__Viveris est un groupe de conseil et d'ingenierie qui accompagne la transformation numérique des entreprises et de leurs produits__

--
[horizontal]
Position:: *Devops & Backend & Frontend developer* +
Développeur sénior, R&D virtualisation de serveurs applicatifs fournissant un accès internet via Satellite
--

* Projet {link-openbach}[Openbach, role="external", window="_blank"]
** *Définir une interface Web* permettant la configuration du projet openbach
* Projet {link-marlink}[Marlink, role="external", window="_blank"]
** Consolidation de la base de code existante
** Mise en place de pratiques de travail
*** TDD, Test, Refactoring
** Virtualisation de la solution

Technologies utilisées::

Git, Java, Docker, Shell, Python, React, Ansible


=== LivingObjects

icon:calendar[title="Period"] `Février 2014 -> Avril 2016` +
icon:group[title="Freelance"] {link-living-objects}[LivingObjects, role="external", window="_blank"] +
__Network Analytics Platform__

--
[horizontal]
Position:: *Java - Web - DevOps* +
R&D Développement et déploiement d'une base de données Cassandra-like
--

* Développement d'une base de données pouvant répondre aux contraintes de volume et d'indexation spécifiques au client
* Déploiement "on-premise" sous docker

Technologies utilisées::

Git, Java, Docker, Shell, Angular

=== Audit applicatif

icon:calendar[title="Period"] `Octobre 2016` +
icon:group[title="Freelance"] MonkeyPatch

== Formations

=== Docker + Ansible
icon:calendar[title="Period"] `Janvier 2016` +
icon:group[title="Freelance"] RobustaCode

=== Docker
icon:calendar[title="Period"] `Janvier 2017` +
icon:group[title="Freelance"] DigitalVillage



== Compétences techniques

Conteneurs:: Docker, Compose, Machine, Kubernetes, Swarm

Languages and Specifications::  TypeScript, Java, Python, Go, Erlang, Elixir, Bash, HTML, CSS, AsciiDoc

Software Engineering:: *XP* (Pair programming, Clean Code, TDD), DevOps, Continuous Integration, Continuous Delivery

OS:: Linux (Ubuntu, Debian, Fedora, Alpine)

Tools:: *Git*, Bash, IntelliJ

== Open Source

{link-open-source-docker-images}[Images docker]::
+
* _Toutes les images docker que je maintiens_ +
+

Contributions::
Je suis un membre passif sur les projets open-source que j'utilise, je contribue à leur amélioration par l'intermédiaire de pull requests ou de projets annexes
Tout ce qui est sur {link-open-source-agileek}[cette page] est open-source.

=== Blog

J'écris quelques posts sur {link-blog}[mon blog]

== Conférences & Présentations

=== Touraine Tech 2018

* *Ce que j'aurais aimé savoir en me lançant dans la domotique*
** icon:file[] https://drive.google.com/file/d/1FlaMp9l9eJ9QnKKzwsz-kWI4azyzRCcR/view[Slides, role="external", window="_blank"]

Avec l'essor de l'IOT, de plus en plus de personnes sont tentées par la domotique. Les grandes enseignes s'y mettent, avec plus ou moins de succès. Notre métier nous permet une plus grand liberté dans ce domaine, encore faut-il ne pas se perdre dans ce qui existe.
Je vous propose un tour d'horizon (non exhaustif) de ce qui se fait, les solutions que j'ai choisies pour mon domicile ainsi que des pistes pour ceux qui souhaitent se lancer.

== Langages

* Français : natif
* Anglais : courant (lecture); intermédiaire (écrit, parlé)

== Education


== Centres d'intérêt

* Sport : Squash, Volley
* Séries TV, Cinéma
* Domotique, Open source
